# Generated by Django 5.2.15 on 2026-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
